/* SPDX-FileCopyrightText: 2011-2022 Blender Foundation
 *
 * SPDX-License-Identifier: Apache-2.0 */

#include "node_fresnel.h"
#include "stdcycles.h"

shader node_glass_bsdf(color Color = 0.8,
                       string distribution = "ggx",
                       int Polarizer = 0,
                       float PolarizerAngle = 0.0,
                       float Roughness = 0.2,
                       float IOR = 1.45,
                       float ThinFilmThickness = 0.0,
                       float ThinFilmIOR = 1.33,
                       float DiffractionWeight = 0.0,
                       float DiffractionPitch = 1600.0,
                       float DiffractionDepth = 150.0,
                       float DiffractionDutyCycle = 0.5,
                       int diffraction_two_sided_handle_plus_one = 0,
                       vector Tangent = vector(0.0),
                       normal Normal = N,
                       output closure color BSDF = 0)
{
  color base_color = max(Color, color(0.0));
  float r2 = clamp(Roughness, 0.0, 1.0);
  r2 = r2 * r2;
  float eta = max(IOR, 1e-5);
  float thinfilm_ior = backfacing() ? ThinFilmIOR / eta : ThinFilmIOR;
  eta = backfacing() ? 1.0 / eta : eta;
  color F0 = F0_from_ior(eta);
  color F90 = color(1.0);

  float grating_weight = clamp(DiffractionWeight, 0.0, 1.0);
  BSDF = (1.0 - grating_weight) * generalized_schlick_bsdf(Normal,
                                  vector(0.0),
                                  base_color,
                                  base_color,
                                  r2,
                                  r2,
                                  F0,
                                  F90,
                                  -eta,
                                  distribution,
                                  "polarizer", Polarizer,
                                  "polarizer_angle", PolarizerAngle,
                                  "thinfilm_thickness",
                                  ThinFilmThickness,
                                  "thinfilm_ior",
                                  thinfilm_ior);
  if (grating_weight > 0.0) {
    vector tangent = Tangent == vector(0.0) ? dPdu : Tangent;
    BSDF += grating_weight * diffraction_glass(Normal, tangent, base_color, Roughness,
        IOR, DiffractionPitch, DiffractionDepth, DiffractionDutyCycle,
        ThinFilmIOR, ThinFilmThickness, distribution == "beckmann",
        "diffraction_two_sided_handle_plus_one", diffraction_two_sided_handle_plus_one,
        "polarizer", Polarizer, "polarizer_angle", PolarizerAngle);
  }
}
