#!/usr/bin/env python3
"""Build a static review page from the outline-package evidence bundle."""
import argparse,html,json,os
from pathlib import Path
p=argparse.ArgumentParser(description=__doc__);p.add_argument('--evidence',type=Path,required=True);a=p.parse_args();base=a.evidence.resolve();repo=Path(__file__).resolve().parents[1]
review=json.loads((base/'review.json').read_text());sources=json.loads((base/'source_manifest.json').read_text());copies=json.loads((base/'editable_scenes/manifest.json').read_text())['scenes']
def url(path):return html.escape(os.path.relpath(path,base),quote=True)
def link(path,label):return '<a href="'+url(path)+'">'+html.escape(label)+'</a>'
def card(image,title,scene_name,exr):
 assert image.is_file() and exr.is_file() and scene_name in copies
 return '<article><h3>'+html.escape(title)+'</h3><img loading="lazy" src="'+url(image)+'" alt="'+html.escape(title,quote=True)+'"><p>'+link(base/'editable_scenes'/(scene_name+'.blend'),'Editable scene')+' · '+link(exr,'Linear EXR')+'</p></article>'
parts=['''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cycles Metal verified development delivery</title><style>body{font:16px/1.55 system-ui;max-width:1400px;margin:auto;padding:24px;background:#15191e;color:#e4e9ef}a{color:#87c7ff}h1,h2,h3{line-height:1.2}article{background:#20262e;padding:16px;border-radius:8px}img{width:100%;height:auto}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(320px,1fr));gap:16px}.notice{border-left:4px solid #e5b667;padding:12px 20px;background:#28251f}table{border-collapse:collapse}td,th{padding:8px 20px;border-bottom:1px solid #566}code{overflow-wrap:anywhere}</style><h1>Cycles diffraction · Apple Metal</h1><p class="notice">Tested development delivery. General reflected/refracted coherent interference and Multi-GGX diffraction are not implemented. Realistic mode remains experimental. This page does not claim completion of the full production scope.</p>''']
parts+=['<p>'+link(repo/'build/diffraction_delivery_20260927_coherence_outline/Blender.app','Application that generated these renders')+' · '+link(repo/'doc/cycles_diffraction_delivery.md','Usage and supported combinations')+' · '+link(repo/'doc/cycles_coherent_metal_outline.md','Evidence and limitations')+'</p>','<p>This gallery retains the preceding outline build’s provenance. The current selection is documented in the usage guide. Generating executable SHA-256: <code>'+sources['binary_sha256']+'</code>. Fast mode skips response-cache construction. All renders below use fixed samples, adaptive sampling OFF and denoising OFF.</p>','<h2>CD / DVD · combined BDPT and guiding</h2><p>512 samples. Appearance and transport check; residual sampling noise remains.</p><div class="grid">']
disc=repo/'tests/output/diffraction/diffraction_outline_combined_discs_v1/physical_discs_bdpt_guided'
parts+=[card(disc.with_suffix('.png'),'CD 1600 nm / DVD 740 nm','physical_discs_bdpt_guided',disc.with_suffix('.exr')),'</div><h2>Direct scalar interference</h2><p>36 reference renders at 128 samples. No exposure fitting or PT brightness normalization. Phase wavelength changes fringe spacing, not RGB source color.</p><table><tr><th>Transport</th><th>Cases passed</th><th>Maximum absolute RMSE</th></tr>']
for mode in ['pt','bdpt','guided','bdpt_guided']:
 r=review[mode];parts+=['<tr><td>'+mode+'</td><td>'+str(r['cases'])+'</td><td>'+format(r['max_absolute_rmse'],'.7g')+'</td></tr>']
parts+=['</table>']
for mode in ['pt','bdpt','guided','bdpt_guided']:
 parts+=['<details><summary>'+mode+' — nine actual renders</summary><div class="grid">']
 for f in sorted((base/('coherence_'+mode)).glob('*.png')):parts+=[card(f,f.stem,'coherence_'+mode+'_'+f.stem,f.with_suffix('.exr'))]
 parts+=['</div></details>']
parts+=['<h2>Material and native-limit controls</h2><p>Ten renders at 128 samples: Thin Wall and Ashikhmin across Metal PT, BDPT, guiding and CPU OSL, plus flat and uncovered controls. These are finite-output and appearance checks, not convergence proofs.</p><div class="grid">']
for f in sorted(base.glob('thin_wall_*/*.png'))+sorted(base.glob('ashikhmin_*/*.png')):parts+=[card(f,f.parent.name,f.parent.name+'_'+f.stem,f.with_suffix('.exr'))]
parts+=['</div><h2>Timing and retained failures</h2><p>Matched warm CD/DVD PT median: 1.267 seconds versus 1.592 seconds for the preceding additive package (512 samples; EXR writing included). This is a small fixture comparison, not a universal speed ranking.</p><p>Grouped suite timeouts remain recorded. The first BDPT disabled-control comparison failed when mixing scene/process histories; the matched fresh-process comparison passed the unchanged gate. The cause of the history dependence is not established.</p><p>'+link(base/'image_controls.json','Original mixed-history control result')+' · '+link(repo/'tests/output/diffraction/outline_bdpt_control_fresh_v1/comparison.json','Fresh-process control result')+' · '+link(base/'source_manifest.json','Source provenance')+'</p><h2>Earlier broader presentation suite</h2><p>Glass, metallic, Principled, refraction, cover and indirect scenes retain their earlier final_v3 binary provenance. They have not all been rerendered on this package.</p><p>'+link(repo/'tests/output/diffraction/presentation_final_v3/index.html','Earlier scene gallery')+'</p><p>Editable copies have separate render destinations and preserve sample/transport settings. No rendered pixels were modified to assemble this page.</p></html>']
(base/'index.html').write_text('\n'.join(parts));print(base/'index.html')
