#!/usr/bin/env python3
"""Build an honest current-binary gallery from completed refresh reports."""
import argparse
import html
import json
import os
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--presentation', type=Path, required=True)
    parser.add_argument('--check-only', action='store_true')
    parser.add_argument('--contact-sheet', action='store_true')
    parser.add_argument('--evidence', nargs=3, action='append', default=[],
                        metavar=('TITLE', 'IMAGE', 'VERSION_LABEL'))
    args = parser.parse_args()
    root = args.presentation.resolve()
    manifest = json.loads((root / 'manifest.json').read_text())
    required = {'cd_dvd', 'glass', 'glossy', 'metallic', 'principled_film', 'refraction',
                'covered_disc', 'indirect', 'thin_wall', 'ashikhmin', 'two_sided_glass',
                'generalized_dispersion', 'coated_generalized_furnace'}
    assert required <= set(manifest['runs']), 'Current full refresh is incomplete'
    cards = []
    for name, entry in manifest['runs'].items():
        assert entry['exit_code'] == 0
        folder = root / name
        report = json.loads((folder / 'report.json').read_text())
        assert report['sha256'] == manifest['sha256'], 'Historical render cannot be labeled current'
        assert report['adaptive_sampling'] is False
        assert all(item['finite'] for item in report['passes'].values())
        title = name.replace('_', ' ').title()
        raw = Path(report['passes']['noisy']['file'])
        raw_link = os.path.relpath(raw, root)
        cards.append(f'<article><h2>{html.escape(title)}</h2><img src="{name}/denoised.png" alt="{html.escape(title)}">'
                     f'<p>{report["transport"].upper()}, {report["samples"]} fixed samples, OIDN presentation. '
                     'Geometry, camera and resolution retained from the saved template; no convergence claim.</p>'
                     f'<p><a href="{name}/noisy.png">Raw preview</a> · <a href="{raw_link}">Raw EXR</a> · '
                     f'<a href="{name}/denoised.exr">OIDN EXR</a> · <a href="{name}/denoising.blend">Editable scene</a> · '
                     f'<a href="{name}/report.json">Report</a></p></article>')
    evidence = []
    for title, image, version in args.evidence:
        path = Path(image).resolve()
        assert path.is_file()
        link = os.path.relpath(path, root)
        evidence.append(f'<article><h2>{html.escape(title)}</h2><p><strong>{html.escape(version)}</strong> '
                        '— separate existing evidence; not regenerated by this gallery refresh.</p>'
                        f'<img src="{link}" alt="{html.escape(title)}"><p><a href="{link}">Original image</a></p></article>')
    page = '<!doctype html><html lang="en"><meta charset="utf-8"><title>Current diffraction appearance refresh</title>'
    page += '<style>body{background:#171b20;color:#eee;font:16px system-ui;max-width:1400px;margin:30px auto;padding:20px}a{color:#9bd2ff}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(400px,1fr));gap:24px}article{background:#242a32;padding:18px}img{width:100%}</style>'
    page += '<h1>Current diffraction appearance refresh</h1><p>Real Metal renders from the executable identified below. Adaptive sampling OFF. Material previews use OIDN; raw EXRs and editable scenes are retained. Appearance is separate from numerical energy, reciprocity and coherence acceptance.</p>'
    page += f'<p>Executable SHA-256: <code>{manifest["sha256"]}</code> · <a href="manifest.json">Manifest</a></p>'
    page += '<p>Fast return caches cover tested reflective, Glass and Principled branches with bounded constant inputs. Runtime tint and Thin Wall use the documented approximations. Linked cache geometry parameters and general nested-media/arbitrary-BSDF coherent phase are not certified. Coherent transport is bounded to the declared ideal interfaces and event/candidate limits validated for this build; consult the separately labeled numerical evidence.</p>'
    page += '<div class="grid">'+''.join(cards)+'</div><h2>Separately labeled numerical evidence</h2><div class="grid">'+''.join(evidence)+'</div></html>'
    if args.check_only:
        print('Completed current-binary reports verified:', len(cards))
        return
    (root / 'index.html').write_text(page)
    if args.contact_sheet:
        from PIL import Image, ImageDraw
        names = list(manifest['runs'])
        width, height, columns = 360, 310, 3
        sheet = Image.new('RGB', (width * columns, height * ((len(names)+columns-1)//columns)+48), '#171b20')
        draw = ImageDraw.Draw(sheet)
        for index, name in enumerate(names):
            x, y = (index % columns)*width, (index // columns)*height
            with Image.open(root / name / 'denoised.png') as source:
                preview = source.convert('RGB')
                preview.thumbnail((width-12, height-42), Image.Resampling.LANCZOS)
                sheet.paste(preview, (x+(width-preview.width)//2, y+28))
            draw.text((x+8, y+8), name.replace('_', ' ').title(), fill='white')
        draw.text((8, sheet.height-34), 'Actual Metal renders; OIDN previews; fixed samples, adaptive OFF. Original display transforms.', fill='white')
        draw.text((8, sheet.height-18), 'Appearance suite: raw EXRs, editable scenes and per-image provenance in index.html.', fill='white')
        sheet.save(root / 'actual_material_overview.png')
    print(root / 'index.html')


if __name__ == '__main__':
    main()
